#build stage
FROM eclipse-temurin:11 AS builder
COPY . .
RUN ./mvnw clean && ./mvnw package -Dmaven.test.skip

#run stage
FROM eclipse-temurin:11-jre-alpine
RUN mkdir /opt/app
WORKDIR /opt/app
ARG APP_PATH=/opt/app
COPY --from=builder target/*.jar ${APP_PATH}/app.jar
ENTRYPOINT ["java", "-jar", "/opt/app/app.jar"]
