@startuml
autonumber
Client -> Server : POST /admin/login with username, password
Server -> Server : Validate username/password\nGenerate JWT token using secret key
Server -> Client : Return JWT token
||40||
Client -> Server : Request /** with JWT in header
Server -> Server : Validate JWt using secret
Server -> Client : Return the response
@enduml
